# Generated by Django 3.2.5 on 2021-07-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carousel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=30, null=True)),
                ('thumbnail', models.ImageField(upload_to='slider_image/')),
                ('short_discription', models.TextField()),
            ],
        ),
    ]
