# Generated by Django 3.2.5 on 2021-07-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carousel_app', '0002_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='thumbnail',
            field=models.ImageField(upload_to='product_image/'),
        ),
    ]
