# Generated by Django 3.2.5 on 2021-07-27 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0003_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
