# Generated by Django 3.2.5 on 2021-07-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publish',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
